import sys
import os
import pretty_midi
from tkinter import filedialog, Tk

def process_multi_track_midi(midi_file_path):
    """
    Reads all MIDI tracks and interleaves their note events chronologically
    so that multiple speakers play simultaneously with correct relative delays.
    """
    try:
        midi_data = pretty_midi.PrettyMIDI(midi_file_path)
    except Exception as e:
        print(f"Error loading MIDI file: {e}")
        return []

    if not midi_data.instruments:
        print("No tracks found.")
        return []

    note_names = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
    
    # 1. Gather all raw note events across all tracks
    # Each track index corresponds directly to a speaker_id
    raw_events = []
    for speaker_id, instrument in enumerate(midi_data.instruments):
        for note in instrument.notes:
            raw_events.append((note.start, 'on', speaker_id, note))
            raw_events.append((note.end, 'off', speaker_id, note))
            
    # Sort everything purely by time. 
    # If events land on the exact same timestamp, process 'off' before 'on'
    raw_events.sort(key=lambda x: (x[0], 0 if x[1] == 'off' else 1))

    # 2. Track what note is playing for each speaker at any given moment
    active_notes_per_speaker = {i: [] for i in range(len(midi_data.instruments))}
    last_state_per_speaker = {i: "r" for i in range(len(midi_data.instruments))}
    
    program = []
    program.append("# Generated by uMusical_transpile.py - File: " + os.path.basename(midi_file_path))
    program.append("c i=1 e MIDI not supported.")
    program.append("")
    current_time = 0.0
    factor = 1  # Time scale factor matching your setup

    # 3. Sweep forward through time step-by-step
    for event_time, event_type, speaker_id, note in raw_events:
        delta_time = event_time - current_time
        
        # If time actually progressed, record the pause/delay for the previous state
        if delta_time > 0:
            program.append(f"d {delta_time * factor}")
            current_time = event_time

        # Update the active note list for this specific speaker
        if event_type == 'on':
            active_notes_per_speaker[speaker_id].append(note)
        elif event_type == 'off':
            if note in active_notes_per_speaker[speaker_id]:
                active_notes_per_speaker[speaker_id].remove(note)

        # Determine what *should* be playing right now on this speaker (highest note priority)
        actives = active_notes_per_speaker[speaker_id]
        if actives:
            highest_note = max(actives, key=lambda n: n.pitch)
            pitch = highest_note.pitch
            name = note_names[pitch % 12]
            octave = (pitch // 12) - 1
            current_state = f"{name}{octave}"
        else:
            current_state = "r"

        # If the speaker's sound changed at this timestamp, issue the command immediately
        if current_state != last_state_per_speaker[speaker_id]:
            if current_state == "r":
                program.append(f"s {speaker_id + 1}")
            else:
                program.append(f"n {speaker_id + 1} {current_state}")
            last_state_per_speaker[speaker_id] = current_state

    # 4. Turn off all speakers at the very end of the file
    for speaker_id in last_state_per_speaker:
        program.append(f"s {speaker_id + 1}")
    program.insert(1, f"# Speakers required: {len(midi_data.instruments)}")
    program.insert(3, f"c c<{len(midi_data.instruments)} e Speaker count not sufficient, requires {len(midi_data.instruments)}.")
    return program

if __name__ == "__main__":
    root = Tk()
    root.withdraw()
    
    midi_path = sys.argv[1] if len(sys.argv) > 1 else filedialog.askopenfilename(filetypes=[("MIDI Files", ["*.mid","*.midi"])])
    
    if midi_path:
        print("Analyzing tracks and building synchronous timeline...")
        program_commands = process_multi_track_midi(midi_path)
        
        if program_commands:
            with open(filedialog.asksaveasfilename(filetypes=["uMusic Files", ["*.umusic"]]), "w") as f:
                f.write("\n".join(program_commands))
            print("Successfully compiled interleaved tracks into output_mcu.umusic!")
